### ISSUE TITLE
《OpenTSN4.0》的项目部署疑问

### ISSUE THREAD

**Issue by guzhirong** [JunnanLi/FL-M32_Runtime#1]
尊敬的OpenTSN开发者您好！
由于没有找到您的联系方式，因此只能在这里向您提问。
我的疑问是：
1.OpenTSN的软件部分是在risc-v上跑的，该代码是为一个“修改版的Cv32e40p (RV32IMC) 处理器核心上编写的，请问这套risc-v处理器核心可以在哪里获取到吗？
2.我有很多基于Zynq UltraScale+ MPSoC的开发板，能否将整套代码部署上去呢？还是一定要购买《从0深入OpenTSN4.0_v1.5》中提及的<OpenTSN 专用 FPGA 矩阵卡>才可以使用整套OpenTSN呢？

我想使用OpenTSN这款开源的工程，配置TSN交换机，通过修改部分协议达到研究目的，我的整个课题都仅作为研究目的，不涉及任何商业。

感谢您的耐心观看，期待您的答复！

**Comment by JunnanLi** [comment]
您好。
1. 目前OpenTSN控制器程序是集中式的，运行在外部主机上（控制器）。riscv这部分负责1）解析控制器下发的调度规则；2）定时上报交换机状态；3）我们采用软硬件协同的时间同步策略，下一步将由riscv负责软件部分。risc-v处理器核采用的是ETH的开源核（cv32e40p），通过https://github.com/openhwgroup/cv32e40p获取。
2. OpenTSN本身开源的是软件、硬件程序，可以支持各类FPGA。目前，我们移植过Xilinx（AMD），Altera（Intel），国产的复旦微，都是可以的。所以，您提及的Zynq UltraScale+ MPSoC的开发板完全可以支持OpenTSN，您只需要替换代码中的RAM/FIFO/CLK IP，以及重新约束网口的pin即可。
此外，您有什么疑问也可以通过电话联系我，18670063317（微信同号）。










--

厉俊男
国防科技大学     计算机学院


Li Junnan
College of Computer Science, National University of Defense Technology




在 2023-11-01 11:13:34，"guzhirong" ***@***.***> 写道：

尊敬的OpenTSN开发者您好！
由于没有找到您的联系方式，因此只能在这里向您提问。
我的疑问是：
1.OpenTSN的软件部分是在risc-v上跑的，该代码是为一个“修改版的Cv32e40p (RV32IMC) 处理器核心上编写的，请问这套risc-v处理器核心可以在哪里获取到吗？
2.我有很多基于Zynq UltraScale+ MPSoC的开发板，能否将整套代码部署上去呢？还是一定要购买《从0深入OpenTSN4.0_v1.5》中提及的<OpenTSN 专用 FPGA 矩阵卡>才可以使用整套OpenTSN呢？

我想使用OpenTSN这款开源的工程，配置TSN交换机，通过修改部分协议达到研究目的，我的整个课题都仅作为研究目的，不涉及任何商业。

感谢您的耐心观看，期待您的答复！
